### ISSUE TITLE
Task doesn't show up in search if Ephemeral keyword is used

### ISSUE THREAD

**Issue by azilber** [microsoft/azure-pipelines-ephemeral-agents#4]
After the initial install from the Marketplace, using either classical pipelines or yaml it does not work.

With classical pipelines there is a grey "installed" and no tasks available.  Any attempts at using it with yaml yields an error.

I've gone over it with Microsoft support and they say the issue is with the extension, and they're unable to help further, although they're trying to see if they can get some backend logs.

<img width="604" alt="Screenshot 2020-03-12 at 12 12 59 AM" src="https://user-images.githubusercontent.com/691270/76499833-6adede80-647a-11ea-8448-1a3868334c72.png">

**Comment by tspascoal** [comment]
Sorry you are having issues, but the task doesn't has any control over the UI or if the tasks are installed or not.

I'm going to try to get some answers for you

**Comment by tspascoal** [comment]
In the meanwhile which error are you seeing in YAML? (besides not being visible in the assistant?

When you execute the pipeline, in the initialize job step logs do you see something along these lines?

>Download all required tasks.
Downloading task: AzureContainerAgentCreate (0.9.0)

**Comment by tspascoal** [comment]
I think I've figured out the problem.

The problem lies in the keyword you have used for the search (and the lack of ephemeral keyword in the task itself) 

If you scroll on the task list, you will find it

![image](https://user-images.githubusercontent.com/7847935/76517614-84b9fa80-6455-11ea-83b4-5266bf857d79.png)

And if you search for `azure container` you will also be able to find it.

![image](https://user-images.githubusercontent.com/7847935/76517665-9bf8e800-6455-11ea-894a-faeab7727c02.png)

I will rename the issue with the cause of the problem as well as fix the description of the task to include the `ephemeral` keyword to make it more discoverable.

Can you confirm this behavior?

**Comment by azilber** [comment]
Hi Tiago,

  You're absolutely right!   I can confirm that's the issue.  I was
searching for "ephemeral" and finding nothing, assumed no tasks were being
registered.   Should have read the Github docs!
  The Yaml issue was a separate permission issue that we've resolved
already.

Thank you so much!
Alex

**Comment by tspascoal** [comment]
Release 1.0.1 (already in the marketplace) improves searchability by including the ephemeral keyword in the task description.
